### ISSUE TITLE
简单构造的json字符串通过http传输在浏览器中json字符串中会收到转移字符

### ISSUE THREAD

**Issue by wangqinghe95** [zhoutk/zjson#1]
hi，我最近在写前后端业务（个人项目），C++后端构造的一个简单的JSON风格的字符串以http 的content传输出去，但是在前端浏览器中会发现有转义字符的出现。我排查了一下后端的字符串长度是不存在（strlen(string))转移字符占据的内存的。然后使用curl命令直接访问这个接口，返回的数据也是没有问题的。我不知道在C++后端进行字符的序列化，但是我理解的序列化和这个应该没有关系。不知道大佬知不知道这个问题产生的原因

**Comment by zhoutk** [comment]
服务端返回信息格式是否是设置为 "application/json"？
