### ISSUE TITLE
当嵌套json里面有相同的key值怎么处理？

### ISSUE THREAD

**Issue by 2776012999** [zhoutk/zjson#3]
{
"eqp": {
"eqpCode": 1,
"eqpNote": "信息位置等"
},
"screen": {
"Width": 1440,
"Height": 900,
"Quality": 100,
"Zoom": 100
},
"stream": {
"Width": 1280,
"Height": 720,
"strFps": 30
},
"ctrl": {
"ctrlType": 0
}
}
如上json 怎么正确取得 width的值？谢谢

**Comment by zhoutk** [comment]
假定这个变量为jv，则，jv["screen"]["Width"], jv["stream"]["Width"] 两种模式应该能取出相应的Width值，find函数，现在只支持取出第一个。
